# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Clutch Analytics
tagline:          'Building it since 2013'
description:      "Now, more than ever.\nWe build solutions.\nMore human than human.\nNostra Sponte."
url:              http://clutchanalytics.com
baseurl:          /

author:
  name:           'Clutch Analytics'
  url:            https://www.linkedin.com/company/clutch-analytics

paginate:         5

# Custom vars
github:           https://github.com/clutchanalytics
email:            austin@clutchanalytics.com

authors:
  HashNuke:
    name: Akash Manohar
    gravatar: 654dd3aa73158b8aabbab50f719038bb
    email: mail@hashnuke.com
    web: http://hashnuke.com
    twitter: HashNuke
    github: HashNuke

  devinus:
    name: Devin Torres
    gravatar: afdd09cd01b1049d2ac009e25f8e2958
    email: devin@devintorr.es
    web: http://devintorr.es
    twitter: devinus
    github: devinus
